window.NF_PROJECTS = [
  { id: 1, title: "Previsão de demanda", category: "IA", year: "2026", description: "Modelo preditivo para antecipar variações de demanda e apoiar decisões de planejamento.", tools: ["Python", "Pandas", "Scikit-learn"], metric: "−18%", metricLabel: "erro de previsão", visual: "line", challenge: "Reduzir a incerteza no planejamento e entender quais variáveis influenciam as oscilações de demanda.", solution: "Construção de um pipeline de preparação, análise temporal e comparação de modelos preditivos, com validação orientada às necessidades do negócio.", result: "Uma previsão mais consistente, acompanhada de métricas claras e uma visualização que permite interpretar os períodos de maior risco.", code: ["data = pd.read_csv('demand.csv')", "X_train, X_test = split_by_time(data)", "model.fit(X_train, y_train)", "forecast = model.predict(next_period)"] },
  { id: 2, title: "Painel executivo", category: "Dashboard", year: "2026", description: "Dashboard para acompanhamento de indicadores estratégicos e identificação rápida de desvios.", tools: ["Power BI", "SQL", "DAX"], metric: "12", metricLabel: "KPIs integrados", visual: "bars", challenge: "Consolidar indicadores dispersos e diminuir o tempo necessário para entender o desempenho da operação.", solution: "Modelagem dos dados, definição de métricas com regras únicas e criação de uma hierarquia visual voltada à leitura executiva.", result: "Doze indicadores reunidos em uma visão comparável, com filtros, tendências e alertas para desvios relevantes.", code: ["WITH metrics AS (", "  SELECT date, revenue, target", "  FROM analytics.daily_results", ") SELECT * FROM metrics;"] },
  { id: 3, title: "Segmentação de clientes", category: "Dados", year: "2025", description: "Análise de comportamento e agrupamento de perfis para apoiar estratégias mais relevantes.", tools: ["Python", "SQL", "Clustering"], metric: "05", metricLabel: "perfis encontrados", visual: "scatter", challenge: "Entender diferenças de comportamento que não eram visíveis em médias gerais.", solution: "Exploração de variáveis, normalização e agrupamento por similaridade, seguida da interpretação de cada perfil encontrado.", result: "Cinco grupos acionáveis, descritos por comportamento e potencial, facilitando decisões de comunicação e atendimento.", code: ["features = scale(customer_data)", "clusters = KMeans(n_clusters=5)", "labels = clusters.fit_predict(features)", "profile(labels)"] },
  { id: 4, title: "Classificador inteligente", category: "IA", year: "2025", description: "Solução para classificar registros automaticamente e reduzir tarefas manuais repetitivas.", tools: ["NLP", "Python", "API"], metric: "91%", metricLabel: "de precisão", visual: "matrix", challenge: "Organizar um grande volume de registros textuais que exigiam classificação manual.", solution: "Preparação do texto, avaliação de abordagens de NLP e exposição do modelo por uma API simples para integração.", result: "Classificação automática com 91% de precisão e tratamento específico para casos de baixa confiança.", code: ["text = preprocess(raw_message)", "vector = encoder.transform(text)", "label, confidence = model.predict(vector)", "return label if confidence > .80 else 'review'"] },
  { id: 5, title: "Pipeline de relatórios", category: "Automação", year: "2025", description: "Automação da coleta, tratamento e distribuição de relatórios recorrentes.", tools: ["Python", "APIs", "Excel"], metric: "8h", metricLabel: "poupadas por semana", visual: "flow", challenge: "Eliminar etapas repetitivas e diminuir erros no fechamento de relatórios semanais.", solution: "Integração das fontes por API, aplicação automática das regras de tratamento e geração padronizada dos arquivos finais.", result: "Oito horas semanais liberadas e um processo rastreável, com logs e alertas quando alguma fonte apresenta falha.", code: ["raw = api.fetch(period='weekly')", "clean = transform(raw)", "validate(clean)", "export_report(clean, format='xlsx')"] },
  { id: 6, title: "Análise de desempenho", category: "Dados", year: "2025", description: "Investigação exploratória para explicar variações e localizar os principais fatores de desempenho.", tools: ["SQL", "Python", "Estatística"], metric: "+24%", metricLabel: "oportunidade mapeada", visual: "donut", challenge: "Explicar por que unidades semelhantes apresentavam resultados muito diferentes no mesmo período.", solution: "Análise exploratória por dimensões, testes de hipótese e cruzamento com variáveis operacionais e comerciais.", result: "Identificação de uma oportunidade potencial de 24% e dos fatores prioritários para um plano de ação.", code: ["segments = df.groupby(['unit', 'channel'])", "variation = compare(segments, baseline)", "drivers = rank_correlations(variation)", "report(drivers[:5])"] },
  { id: 7, title: "Monitor de operações", category: "Dashboard", year: "2024", description: "Visão operacional em tempo quase real para acompanhamento de volume, qualidade e produtividade.", tools: ["Power BI", "ETL", "SQL"], metric: "03", metricLabel: "fontes conectadas", visual: "columns", challenge: "Criar uma leitura única de volume, qualidade e produtividade atualizada ao longo do dia.", solution: "Pipeline de ETL conectando três fontes e painel operacional com níveis de atenção e detalhamento por equipe.", result: "Monitoramento centralizado e identificação antecipada de gargalos, diminuindo a dependência de consolidações manuais.", code: ["sources = ['volume', 'quality', 'team']", "fact = etl.merge(sources, key='timestamp')", "refresh(fact, interval='30min')", "alert(on='threshold_breach')"] },
  { id: 8, title: "Validação de dados", category: "Automação", year: "2024", description: "Rotina automatizada para detectar inconsistências antes que elas cheguem aos relatórios.", tools: ["Python", "SQL", "Data Quality"], metric: "−63%", metricLabel: "inconsistências", visual: "checks", challenge: "Impedir que falhas silenciosas nas fontes comprometessem análises e relatórios posteriores.", solution: "Biblioteca de regras para schema, nulos, faixas, duplicidades e consistência entre tabelas, com registro de cada execução.", result: "Redução de 63% nas inconsistências identificadas após a publicação dos relatórios.", code: ["assert_schema(data, contract)", "check_nulls(data, required_fields)", "check_ranges(data, business_rules)", "log_quality_score(data)"] }
];

window.NF_VISUALS = {
  line: `<svg viewBox="0 0 420 190" aria-hidden="true"><path class="v-grid" d="M0 35H420M0 80H420M0 125H420M0 170H420"/><path class="v-area" d="M0 165L52 143L104 150L156 103L208 120L260 72L312 86L364 38L420 48V190H0Z"/><path class="v-line" d="M0 165L52 143L104 150L156 103L208 120L260 72L312 86L364 38L420 48"/></svg>`,
  bars: `<div class="bar-chart" aria-hidden="true"><i style="height:38%"></i><i style="height:62%"></i><i style="height:48%"></i><i style="height:82%"></i><i style="height:70%"></i><i style="height:94%"></i></div>`,
  scatter: `<div class="scatter" aria-hidden="true">${[12,28,44,61,75,87,18,34,52,69,82,93].map((x, index) => `<i style="left:${x}%;top:${18 + ((index * 31) % 66)}%"></i>`).join("")}</div>`,
  matrix: `<div class="matrix" aria-hidden="true">${Array.from({length:35}, (_, index) => `<i class="${[3,9,12,18,25,29,34].includes(index) ? "on" : ""}"></i>`).join("")}</div>`,
  flow: `<div class="flow" aria-hidden="true"><span>INPUT</span><i>→</i><span>PROCESS</span><i>→</i><span>OUTPUT</span></div>`,
  donut: `<div class="donut" aria-hidden="true"><span>76<small>%</small></span></div>`,
  columns: `<div class="columns" aria-hidden="true">${[43,67,55,84,61,92,76,88].map((height,index) => `<i style="height:${height}%"><span>${index+1}</span></i>`).join("")}</div>`,
  checks: `<div class="checks" aria-hidden="true"><span><i>✓</i>schema_valid</span><span><i>✓</i>null_check</span><span><i>✓</i>range_test</span><span><i>✓</i>duplicates</span></div>`
};
